
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('podcasts').del(),

    // Inserts seed entries
    knex('podcasts').insert([{title: 'MergeLane incubates women-lead businesses', description: 'They started with three women who had great ideas. Now MergeLane is a full time incubator for women-lead startups. The founders give us insights into what makes an excellent candidate and why they are having trouble finding them.', date: '7/7/2016', link: 'www.google.com', image_url: 'http://www.denverpost.com/wp-content/uploads/2016/04/20150210__20150211_A10_BZ11MERGELANEp1.jpg?w=654'}, {title: 'Boulder Digital Collective', description: 'A female only agency? Stacie V knew a lot of stellar developers and decided she wanted to connect them in a meaningul way. She tells the story of getting their names out there through the Boulder Digital Collevtive.', date: '7/5/2016', link: 'www.google.com', image_url: 'http://static1.squarespace.com/static/57215e5dc6fc0829df286374/5721614545bf21749a2144b1/57216ea08a65e20d87783ca9/1463706799134/Stacie+LaughLR.jpg?format=1000w'}, {title: 'A tale of two founders', description: 'They met on a plane. Three years later, they were spending late nights building their dream. Meet the two women behind SparkPlug.', date: '6/22/2016', link: 'www.google.com', image_url: 'https://revolar.com/wp-content/uploads/2016/02/JaqRevolar-0009.jpg'}, {title: 'Interview with Sue Anderson', description: 'Sue Anderson is the first female President of Charge, the networking company that is taking over the U.S. and Canada. She started off as an Account Manager, so how did she work her way up?', date: '7/3/2016', link: 'www.google.com', image_url: 'http://extras.mnginteractive.com/live/media/site21/2016/0128/20160128_122202_BZ27MERGELANE_KO19025.jpg'}, {title: 'Stormy waters for AI', description: 'Lisa Thompson builds smart machines for Roboto. We talk with her about the moral implications of her work and who should maintain responsabilitie for an AI product through-out its life cycle', date: '6/29/2016', link: 'www.google.com', image_url: 'http://nerdsmagazine.com/wp-content/uploads/2016/02/shutterstock_135053870-e1396029269930.jpg'}, {title: 'Turning idea into business', description: 'Mary Jenner started with a stand at a farmers market and has built an empire of handcrafted goods. She gives us a few lessons on getting over the fear of failure that most entrepreneurs deal with.', date: '6/25/2016', link: 'www.google.com', image_url: 'https://img.buzzfeed.com/buzzfeed-static/static/2013-11/enhanced/webdr05/20/17/grid-cell-13775-1384988034-19.jpg'}])
  );
};
